version: "3.9"

services:
  app:
    build: .
    image: propbot:local
    container_name: propbot_app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
