version: "3.9"

services:
  propbot-app:
    image: ghcr.io/${REPO:-my-org}/propbot:${TAG:-main}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propbot_app_prod
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      BUILD_VERSION: ${TAG:-main}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://127.0.0.1:8000/healthz | grep -q '\\"ok\\": true'",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
