name: Bug report
description: Сообщить об ошибке
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: Описание
      placeholder: Что произошло, что ожидали
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
  - type: input
    id: env
    attributes:
      label: Среда (OS, Python, профиль)
