# Reason codes (константы для логов/событий)
RC_HEALTH_OK = "HEALTH_OK"
RC_CONFIG_APPLY_OK = "CONFIG_APPLY_OK"
RC_CONFIG_VALIDATE_FAIL = "CONFIG_VALIDATE_FAIL"
RC_RECON_MISMATCH = "RECON_MISMATCH"
RC_HOLD_TRIGGERED = "HOLD_TRIGGERED"
RC_RESUME_APPROVED = "RESUME_APPROVED"
