"""Metric helpers exposed for reuse across the application."""

from .runtime import (
    AUTO_TRADE_GAUGE,
    DAILY_LOSS_BREACH_GAUGE,
    RECON_DIFFS_GAUGE,
    RECON_EXCEPTIONS_COUNTER,
    RISK_BREACHES_COUNTER,
    TRADES_EXECUTED_COUNTER,
    WATCHDOG_STATE_GAUGE,
    record_risk_breach,
    record_trade_execution,
    set_auto_trade_state,
    set_daily_loss_breach,
    set_watchdog_state,
)
from .slo import (
    DAILY_LOSS_BREACHED_GAUGE,
    ORDER_CYCLE_HISTOGRAM,
    SKIPPED_COUNTER,
    WATCHDOG_OK_GAUGE,
    WS_GAP_HISTOGRAM,
    inc_skipped,
    observe_ws_gap,
    order_cycle_timer,
    record_order_cycle,
    reset_for_tests,
    set_daily_loss_breached,
    set_watchdog_ok,
)
from .observability import (
    API_LATENCY,
    MARKET_DATA_STALENESS,
    METRICS_SLO_ENABLED,
    ORDER_ERRORS_COUNTER,
    WATCHDOG_STATE_GAUGE,
    observe_api_latency,
    observe_api_request,
    record_order_error,
    register_slo_metrics,
    set_market_data_staleness,
    set_watchdog_health,
    set_watchdog_state_metric,
)
from .execution import (
    OPEN_ORDERS_GAUGE,
    ORDER_RETRIES_TOTAL,
    STUCK_ORDERS_TOTAL,
    STUCK_RESOLVER_ACTIVE_INTENTS,
    STUCK_RESOLVER_RETRIES_TOTAL,
)
from .orders import (
    IDEMPOTENCY_HIT_TOTAL,
    OPEN_INTENTS_GAUGE,
    ORDER_INTENT_TOTAL,
    ORDER_SUBMIT_LATENCY,
    observe_replace_chain,
    record_open_intents,
)
from .recon import RECON_AUTO_HOLD_COUNTER, RECON_DIFF_NOTIONAL_GAUGE, RECON_STATUS_GAUGE
from .pretrade import PRETRADE_AUTOFIX_TOTAL, PRETRADE_BLOCKS_TOTAL, PRETRADE_CHECKS_TOTAL
from .risk_governor import (
    increment_window as increment_risk_window,
    record_blocked_order,
    record_risk_check,
    set_error_rate as set_risk_error_rate,
    set_success_rate as set_risk_success_rate,
    set_throttled as set_risk_throttled,
    set_velocity,
)

set_risk_velocity = set_velocity

__all__ = [
    "AUTO_TRADE_GAUGE",
    "DAILY_LOSS_BREACH_GAUGE",
    "RECON_EXCEPTIONS_COUNTER",
    "RECON_DIFFS_GAUGE",
    "RECON_DIFF_NOTIONAL_GAUGE",
    "RECON_STATUS_GAUGE",
    "RECON_AUTO_HOLD_COUNTER",
    "RISK_BREACHES_COUNTER",
    "TRADES_EXECUTED_COUNTER",
    "WATCHDOG_STATE_GAUGE",
    "DAILY_LOSS_BREACHED_GAUGE",
    "ORDER_CYCLE_HISTOGRAM",
    "SKIPPED_COUNTER",
    "WATCHDOG_OK_GAUGE",
    "WS_GAP_HISTOGRAM",
    "API_LATENCY",
    "MARKET_DATA_STALENESS",
    "ORDER_ERRORS_COUNTER",
    "WATCHDOG_STATE_GAUGE",
    "METRICS_SLO_ENABLED",
    "ORDER_INTENT_TOTAL",
    "IDEMPOTENCY_HIT_TOTAL",
    "OPEN_INTENTS_GAUGE",
    "OPEN_ORDERS_GAUGE",
    "ORDER_SUBMIT_LATENCY",
    "ORDER_RETRIES_TOTAL",
    "STUCK_RESOLVER_ACTIVE_INTENTS",
    "STUCK_RESOLVER_RETRIES_TOTAL",
    "STUCK_ORDERS_TOTAL",
    "observe_replace_chain",
    "record_open_intents",
    "PRETRADE_CHECKS_TOTAL",
    "PRETRADE_AUTOFIX_TOTAL",
    "PRETRADE_BLOCKS_TOTAL",
    "record_trade_execution",
    "record_risk_breach",
    "set_auto_trade_state",
    "set_watchdog_state",
    "set_daily_loss_breach",
    "inc_skipped",
    "observe_ws_gap",
    "order_cycle_timer",
    "record_order_cycle",
    "reset_for_tests",
    "set_daily_loss_breached",
    "set_watchdog_ok",
    "observe_api_latency",
    "observe_api_request",
    "set_market_data_staleness",
    "record_order_error",
    "set_watchdog_health",
    "set_watchdog_state_metric",
    "register_slo_metrics",
    "set_risk_success_rate",
    "set_risk_error_rate",
    "set_risk_throttled",
    "increment_risk_window",
    "record_risk_check",
    "record_blocked_order",
    "set_velocity",
    "set_risk_velocity",
]
