"""Metric helpers exposed for reuse across the application."""

from .runtime import (
    AUTO_TRADE_GAUGE,
    DAILY_LOSS_BREACH_GAUGE,
    RECON_DIFFS_GAUGE,
    RECON_EXCEPTIONS_COUNTER,
    RISK_BREACHES_COUNTER,
    TRADES_EXECUTED_COUNTER,
    WATCHDOG_STATE_GAUGE,
    record_risk_breach,
    record_trade_execution,
    set_auto_trade_state,
    set_daily_loss_breach,
    set_watchdog_state,
)
from .slo import (
    DAILY_LOSS_BREACHED_GAUGE,
    ORDER_CYCLE_HISTOGRAM,
    SKIPPED_COUNTER,
    WATCHDOG_OK_GAUGE,
    WS_GAP_HISTOGRAM,
    inc_skipped,
    observe_ws_gap,
    order_cycle_timer,
    record_order_cycle,
    reset_for_tests,
    set_daily_loss_breached,
    set_watchdog_ok,
)
from .observability import (
    API_LATENCY,
    MARKET_DATA_STALENESS,
    METRICS_SLO_ENABLED,
    ORDER_ERRORS_COUNTER,
    WATCHDOG_STATE_GAUGE,
    observe_api_latency,
    observe_api_request,
    record_order_error,
    register_slo_metrics,
    set_market_data_staleness,
    set_watchdog_health,
    set_watchdog_state_metric,
)
from .risk_governor import (
    increment_window as increment_risk_window,
    set_error_rate as set_risk_error_rate,
    set_success_rate as set_risk_success_rate,
    set_throttled as set_risk_throttled,
)

__all__ = [
    "AUTO_TRADE_GAUGE",
    "DAILY_LOSS_BREACH_GAUGE",
    "RECON_EXCEPTIONS_COUNTER",
    "RECON_DIFFS_GAUGE",
    "RISK_BREACHES_COUNTER",
    "TRADES_EXECUTED_COUNTER",
    "WATCHDOG_STATE_GAUGE",
    "DAILY_LOSS_BREACHED_GAUGE",
    "ORDER_CYCLE_HISTOGRAM",
    "SKIPPED_COUNTER",
    "WATCHDOG_OK_GAUGE",
    "WS_GAP_HISTOGRAM",
    "API_LATENCY",
    "MARKET_DATA_STALENESS",
    "ORDER_ERRORS_COUNTER",
    "WATCHDOG_STATE_GAUGE",
    "METRICS_SLO_ENABLED",
    "record_trade_execution",
    "record_risk_breach",
    "set_auto_trade_state",
    "set_watchdog_state",
    "set_daily_loss_breach",
    "inc_skipped",
    "observe_ws_gap",
    "order_cycle_timer",
    "record_order_cycle",
    "reset_for_tests",
    "set_daily_loss_breached",
    "set_watchdog_ok",
    "observe_api_latency",
    "observe_api_request",
    "set_market_data_staleness",
    "record_order_error",
    "set_watchdog_health",
    "set_watchdog_state_metric",
    "register_slo_metrics",
    "set_risk_success_rate",
    "set_risk_error_rate",
    "set_risk_throttled",
    "increment_risk_window",
]
