name: Testnet Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Placeholder smoke run"
