name: Testnet Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  smoke:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "placeholder: smoke бежит только на main или вручную, т.к. нужны секреты"
