name: Testnet Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - env:
          PYTHONPATH: .
          SAFE_MODE: "true"
          DRY_RUN: "true"
        run: python -m app.cli.dryrun --once --artifact artifacts/nightly_dryrun_plan.json
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-dryrun-plan
          path: artifacts/nightly_dryrun_plan.json
